"""Round-2 referee fixes for the rung-resolved analysis (supersedes the
first-pass pure_rung_dfs.py and the orphan pure_rung_thermal_var.json).

Fixes implemented here:

1. CLEAN THERMAL POOLS.  The first pass used ``thermal_ensemble``, whose
   exclusion list is the top-(L+1) Z2-overlap mask; the outer FSA rungs are
   not in that mask, so at E=6.572/7.710 the "thermal" pools contained the
   scar eigenstates themselves.  Here the eigenstate nearest to EVERY FSA
   rung is excluded explicitly.

2. THERMAL Var J^2 GENERATED BY THIS SCRIPT (no orphan JSON), deduplicated
   over chiral partners, with the distinct-state count reported.

3. PHYSICALLY COARSE-GRAINED CASIMIR MEASUREMENT.  The emergent J^2 at
   L=14 has a dense, almost nondegenerate spectrum (987 values, 6 gaps
   >0.5), so a fine-grained projective J^2 shot resolves ANY two-dimensional
   code -- the scar C_R is then rung-independent counting statistics and no
   variance mechanism can be tested.  Here J^2 outcomes are binned to the
   nearest j(j+1) (j = 0..7), the multiplet structure of the emergent
   algebra; within-bin codes can now survive a shot, so Casimir variance
   becomes an operationally meaningful knob.

4. WINDOW SENSITIVITY OF THE J^2 CHANNEL at the canonical rung
   (window 0.3 vs 0.5 at fixed seed), which Appendix C never covered.

Writes results/pure_rung_dfs2.json.
"""

import json
import os

import numpy as np

from scarcode import PXPModel, diagonalize, identify_scars
from scarcode.monitor import MonitoredPXP, TrajectoryConfig
from scarcode.su2 import casimir, h_plus

L = 14
DT = 0.6
NTRAJ = 200
KPAIRS = 10
SEED = 1
PS = (0.04, 0.08, 0.12)
TARGET_ES = (2.737, 4.058, 5.343, 6.572, 7.710)

OUT = os.path.join(os.path.dirname(__file__), "..", "results",
                   "pure_rung_dfs2.json")


def propagator(spec, dt):
    phase = np.exp(-1j * spec.energies * dt)
    return (spec.vectors * phase) @ spec.vectors.conj().T


def fsa_tower(model):
    z2 = model.neel_state()
    Hp = h_plus(model)
    basis, v = [z2], z2
    for _ in range(model.L):
        v = Hp @ v
        for b in basis:
            v = v - (b @ v) * b
        n = np.linalg.norm(v)
        if n < 1e-10:
            break
        basis.append(v / n)
        v = basis[-1]
    B = np.array(basis).T
    h = B.T @ (model.hamiltonian() @ B)
    w, u = np.linalg.eigh(h)
    return w, B @ u


def binned_casimir_monitor(model, U, J2):
    """MonitoredPXP whose operator outcomes are binned to the nearest
    j(j+1) -- the emergent-multiplet coarse-graining."""
    mon = MonitoredPXP(model, dt=DT, U=U, operator=J2)
    wO = np.sort(np.linalg.eigvalsh(J2))
    js = np.arange(0, model.L // 2 + 1)
    targets = js * (js + 1)
    mon.op_labels = np.array(
        [int(np.argmin(np.abs(targets - x))) for x in wO])
    return mon


def var_j2(J2, v):
    m1 = v @ (J2 @ v)
    return float(v @ (J2 @ (J2 @ v)) - m1 ** 2)


def clean_pool(spec, fsa_nearest, target, window):
    """Non-tower, non-FSA-nearest, low-overlap eigenstates near target."""
    idx = [k for k in range(len(spec.energies))
           if abs(spec.energies[k] - target) < window
           and not spec.scar_mask[k]
           and k not in fsa_nearest
           and spec.z2_overlap[k] < 0.02
           and abs(spec.energies[k]) > 0.3]
    return sorted(idx, key=lambda k: abs(spec.energies[k] - target))


def make_pairs(spec, fsa_nearest, E, window, rng):
    pa = clean_pool(spec, fsa_nearest, -E, window)
    pb = clean_pool(spec, fsa_nearest, +E, window)
    rng.shuffle(pa)
    rng.shuffle(pb)
    pairs = list(zip(pa[:KPAIRS], pb[:KPAIRS]))
    return pairs, len(set(pa) | set(pb))


def cr(mon, v0, v1, p, ntraj, measure):
    cfg = TrajectoryConfig(p=p, n_steps=40, dt=DT, measure=measure,
                           record_every=4)
    return mon.coherent_information(v0, v1, cfg, ntraj, SEED)["C_R"]


def main():
    model = PXPModel(L)
    spec = diagonalize(model)
    identify_scars(spec, L=L)
    J2 = casimir(model)
    U = propagator(spec, DT)
    w_fsa, fsa = fsa_tower(model)
    fsa_nearest = {int(np.argmax(np.abs(spec.vectors.T @ fsa[:, r]) ** 2))
                   for r in range(fsa.shape[1])}

    mon_bin = binned_casimir_monitor(model, U, J2)
    mon_loc = MonitoredPXP(model, dt=DT, U=U)

    res = dict(L=L, ntraj=NTRAJ, kpairs=KPAIRS, window=0.5, ps=list(PS),
               binning="nearest j(j+1), j=0..7", pairs=[])
    for Etgt in TARGET_ES:
        ip = int(np.argmin(np.abs(spec.energies - Etgt)))
        im = int(np.argmin(np.abs(spec.energies + Etgt)))
        vp, vm = spec.vectors[:, ip], spec.vectors[:, im]
        rung = int(np.argmin(np.abs(w_fsa - Etgt)))
        weight = float(np.abs(fsa[:, rung] @ vp) ** 2)

        rng = np.random.default_rng(SEED)
        pairs, n_distinct = make_pairs(spec, fsa_nearest, Etgt, 0.5, rng)
        # deduplicated thermal Var J^2 over the distinct pool states
        pool_states = sorted({k for ab in pairs for k in ab})
        tvars = [var_j2(J2, spec.vectors[:, k]) for k in pool_states]

        row = dict(E=float(spec.energies[ip]), fsa_weight=weight,
                   var_scar=var_j2(J2, vp),
                   thermal_var_mean=float(np.mean(tvars)) if tvars else None,
                   thermal_var_n_distinct=len(tvars),
                   n_pairs=len(pairs), pool_distinct=n_distinct,
                   scar_in_pool=bool(ip in pool_states or im in pool_states),
                   modes={})
        print(f"E={row['E']:+.3f} w={weight:.3f} VarS={row['var_scar']:.2f} "
              f"VarT={row['thermal_var_mean'] and round(row['thermal_var_mean'],2)} "
              f"(n={len(tvars)}) pairs={len(pairs)} scar_in_pool={row['scar_in_pool']}")
        if len(pairs) < 3:
            print("  -> pool too small, dynamics skipped")
            res["pairs"].append(row)
            json.dump(res, open(OUT, "w"), indent=1)
            continue
        for mode, mon in (("binnedJ2", mon_bin), ("localZ", mon_loc)):
            meas = "operator" if mode == "binnedJ2" else "localZ"
            entry = []
            for p in PS:
                cs = cr(mon, vp, vm, p, NTRAJ, meas)
                tv = [cr(mon, spec.vectors[:, a], spec.vectors[:, b], p,
                         NTRAJ, meas) for a, b in pairs]
                entry.append(dict(p=p, scar=cs,
                                  therm_mean=float(np.mean(tv)),
                                  therm_std=float(np.std(tv, ddof=1)),
                                  dCR=cs - float(np.mean(tv))))
                print(f"  {mode} p={p:.2f}: scar={cs:.4f} "
                      f"therm={np.mean(tv):.4f}+-{np.std(tv, ddof=1):.4f}")
            row["modes"][mode] = entry
        res["pairs"].append(row)
        json.dump(res, open(OUT, "w"), indent=1)

    # window sensitivity of the FINE-GRAINED J^2 channel, canonical rung
    mon_fine = MonitoredPXP(model, dt=DT, U=U, operator=J2)
    ip = int(np.argmin(np.abs(spec.energies - 2.737)))
    im = int(np.argmin(np.abs(spec.energies + 2.737)))
    vp, vm = spec.vectors[:, ip], spec.vectors[:, im]
    wrows = []
    for window in (0.3, 0.5):
        rng = np.random.default_rng(SEED)
        pairs, _ = make_pairs(spec, fsa_nearest, 2.737, window, rng)
        for p in PS:
            cs = cr(mon_fine, vp, vm, p, NTRAJ, "operator")
            tv = [cr(mon_fine, spec.vectors[:, a], spec.vectors[:, b], p,
                     NTRAJ, "operator") for a, b in pairs]
            wrows.append(dict(window=window, p=p, scar=cs,
                              therm_mean=float(np.mean(tv)),
                              dCR=cs - float(np.mean(tv)),
                              n_pairs=len(pairs)))
            print(f"[win] fineJ2 w={window} p={p:.2f}: "
                  f"dCR={wrows[-1]['dCR']:+.4f}")
    res["window_check_fineJ2_canonical"] = wrows
    json.dump(res, open(OUT, "w"), indent=1)
    print("wrote", OUT)


if __name__ == "__main__":
    main()
